min_height: 0.05
max_height: 2.0

angle_min      : !degrees -35.0
angle_max      : !degrees  35.0
angle_increment: !degrees   0.33
scan_time: 0.2   # 5Hz

range_min: 1.3
range_max: 5.0

target_frame: rgbd_laser_link

use_concurrency: 2 #two parallel threads
use_inf        : true

